version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: strapi-postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - strapi

  strapi:
    image: strapi/strapi:latest
    container_name: strapi-cms
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi_password
      DATABASE_SSL: false
      NODE_ENV: development
      APP_KEYS: "toBeModified1,toBeModified2"
      API_TOKEN_SALT: tobemodified
      ADMIN_JWT_SECRET: tobemodified
      JWT_SECRET: tobemodified
      TRANSFER_TOKEN_SALT: tobemodified
    volumes:
      - strapi_data:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    networks:
      - strapi

networks:
  strapi:
    driver: bridge

volumes:
  postgres_data:
  strapi_data: