export interface ResourceLink { title: string; path: string; }
export const RESOURCES_INDEX: Record<string, ResourceLink[]> = {
  'bright-futures-aile': [
    { title: "1. Ay - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/1-ay-aile-in-bilgiler" },
    { title: "10. Yaş - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/10-ya-aile-in-bilgiler" },
    { title: "11. Yaş - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/11-ya-aile-in-bilgiler" },
    { title: "12. Ay - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/12-ay-aile-in-bilgiler" },
    { title: "12. Yaş - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/12-ya-aile-in-bilgiler" },
    { title: "14. Yaş - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/14-ya-aile-in-bilgiler" },
    { title: "15. Ay - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/15-ay-aile-in-bilgiler" },
    { title: "15. Yaş - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/15-ya-aile-in-bilgiler" },
    { title: "18. Ay - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/18-ay-aile-in-bilgiler" },
    { title: "2. Ay - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/2-ay-aile-in-bilgiler" },
    { title: "2. Yaş - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/2-ya-aile-in-bilgiler" },
    { title: "2½ Yaş - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/2-ya-aile-in-bilgiler-v2" },
    { title: "3. Yaş - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/3-ya-aile-in-bilgiler" },
    { title: "4. Ay - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/4-ay-aile-in-bilgiler" },
    { title: "4. Yaş - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/4-ya-aile-in-bilgiler" },
    { title: "5. Yaş - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/5-ya-aile-in-bilgiler" },
    { title: "6. Ay - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/6-ay-aile-in-bilgiler" },
    { title: "6. Yaş - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/6-ya-aile-in-bilgiler" },
    { title: "7. Ay - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/7-ay-aile-in-bilgiler" },
    { title: "7. Yaş - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/7-ya-aile-in-bilgiler" },
    { title: "8. Yaş - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/8-ya-aile-in-bilgiler" },
    { title: "9. Ay - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/9-ay-aile-in-bilgiler" },
    { title: "9. Yaş - Aile İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-aile/9-ya-aile-in-bilgiler" }
  ],
  'bright-futures-cocuk': [
    { title: "10. Yaş - Çocuk İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-cocuk/10-ya-ocuk-in-bilgiler" },
    { title: "11. Yaş - Çocuk İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-cocuk/11-ya-ocuk-in-bilgiler" },
    { title: "12. Yaş - Çocuk İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-cocuk/12-ya-ocuk-in-bilgiler" },
    { title: "13. Yaş - Çocuk İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-cocuk/13-ya-ocuk-in-bilgiler" },
    { title: "14. Yaş - Çocuk İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-cocuk/14-ya-ocuk-in-bilgiler" },
    { title: "15. Yaş - Çocuk İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-cocuk/15-ya-ocuk-in-bilgiler" },
    { title: "17. Yaş - Çocuk İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-cocuk/17-ya-ocuk-in-bilgiler" },
    { title: "7. Yaş - Çocuk İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-cocuk/7-ya-ocuk-in-bilgiler" },
    { title: "8. Yaş - Çocuk İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-cocuk/8-ya-ocuk-in-bilgiler" },
    { title: "9. Yaş - Çocuk İçin Bilgiler", path: "/bilgi-merkezi/bright-futures-cocuk/9-ya-ocuk-in-bilgiler" },
    { title: "Akne Hakkında Bilmen Gerekenler", path: "/bilgi-merkezi/bright-futures-cocuk/akne-hakk-nda-bilmen-gerekenler" },
    { title: "Ergenlik Dönemi - Büyük Değişimlere Hazır Ol", path: "/bilgi-merkezi/bright-futures-cocuk/ergenlik-d-nemi-b-y-k-de-i-imlere-haz-r-ol" },
    { title: "Genç Ergene Doktorundan Mektup", path: "/bilgi-merkezi/bright-futures-cocuk/gen-ergene-doktorundan-mektup" }
  ],
  'asilar': [
    { title: "HPV Aşısı Bilgi Föyü", path: "/bilgi-merkezi/asilar/hpv-a-s-bilgi-f-y" },
    { title: "İnfluenza Aşısı Bilgi Föyü", path: "/bilgi-merkezi/asilar/nfluenza-a-s-bilgi-f-y" },
    { title: "KKK Aşısı Bilgi Föyü", path: "/bilgi-merkezi/asilar/kkk-a-s-bilgi-f-y" },
    { title: "KKKS Aşısı Bilgi Föyü", path: "/bilgi-merkezi/asilar/kkks-a-s-bilgi-f-y" },
    { title: "Meningokok ACWY Aşısı Bilgi Föyü", path: "/bilgi-merkezi/asilar/meningokok-acwy-a-s-bilgi-f-y" },
    { title: "Meningokok B Aşısı Bilgi Föyü", path: "/bilgi-merkezi/asilar/meningokok-b-a-s-bilgi-f-y" },
    { title: "Rotavirüs Aşısı Bilgi Föyü", path: "/bilgi-merkezi/asilar/rotavir-s-a-s-bilgi-f-y" }
  ],
  'gebelik-donemi': [
    { title: "Bebek Beşiği Güvenliği", path: "/bilgi-merkezi/gebelik-donemi/bebek-be-i-i-g-venli-i" },
    { title: "Bebek Odası Güvenliği", path: "/bilgi-merkezi/gebelik-donemi/bebek-odas-g-venli-i" },
    { title: "Doğum Öncesi Emzirmeye Hazırlık", path: "/bilgi-merkezi/gebelik-donemi/do-um-ncesi-emzirmeye-haz-rl-k" },
    { title: "Gebelikte Sağlıklı Beslenme Kılavuzu", path: "/bilgi-merkezi/gebelik-donemi/gebelikte-sa-l-kl-beslenme-k-lavuzu" },
    { title: "Mama Taburesi Kılavuzu", path: "/bilgi-merkezi/gebelik-donemi/mama-taburesi-k-lavuzu" }
  ],
  'gelisim-rehberleri': [
    { title: "1 yaş Gelişimsel öneriler", path: "/bilgi-merkezi/gelisim-rehberleri/1-ya-geli-imsel-neriler" },
    { title: "4 Yaş Gelişimsel Öneriler", path: "/bilgi-merkezi/gelisim-rehberleri/4-ya-geli-imsel-neriler" },
    { title: "5 Yaş Gelişimsel Öneriler", path: "/bilgi-merkezi/gelisim-rehberleri/5-ya-geli-imsel-neriler" },
    { title: "Gelişim Basamakları - 12. Ay ", path: "/bilgi-merkezi/gelisim-rehberleri/geli-im-basamaklar-12-ay" },
    { title: "Gelişim Basamakları - 2. Ay", path: "/bilgi-merkezi/gelisim-rehberleri/geli-im-basamaklar-2-ay" },
    { title: "Gelişim Basamakları - 2. Ay (Yeni)", path: "/bilgi-merkezi/gelisim-rehberleri/geli-im-basamaklar-2-ay-yeni" },
    { title: "Gelişim Basamakları - 4. Ay", path: "/bilgi-merkezi/gelisim-rehberleri/geli-im-basamaklar-4-ay" },
    { title: "Gelişim Basamakları - 4. Ay (Yeni)", path: "/bilgi-merkezi/gelisim-rehberleri/geli-im-basamaklar-4-ay-yeni" },
    { title: "Gelişim Basamakları - 4. Yaş ", path: "/bilgi-merkezi/gelisim-rehberleri/geli-im-basamaklar-4-ya" },
    { title: "Gelişim Basamakları - 6. Ay", path: "/bilgi-merkezi/gelisim-rehberleri/geli-im-basamaklar-6-ay" },
    { title: "Gelişim Basamakları - 6. Ay (Yeni)", path: "/bilgi-merkezi/gelisim-rehberleri/geli-im-basamaklar-6-ay-yeni" },
    { title: "Gelişim Basamakları - 9. Ay ", path: "/bilgi-merkezi/gelisim-rehberleri/geli-im-basamaklar-9-ay" },
    { title: "Gelişim İpuçları ve Etkinlikleri - 4. Yaş ", path: "/bilgi-merkezi/gelisim-rehberleri/geli-im-pu-lar-ve-etkinlikleri-4-ya" }
  ],
  'hastaliklar': [
    { title: "Antibiyotikler", path: "/bilgi-merkezi/hastaliklar/antibiyotikler" },
    { title: "Astım Ataklarından Korunma", path: "/bilgi-merkezi/hastaliklar/ast-m-ataklar-ndan-korunma" },
    { title: "Bademcik İltihabı", path: "/bilgi-merkezi/hastaliklar/bademcik-ltihab" },
    { title: "Çocuklarda Ateş", path: "/bilgi-merkezi/hastaliklar/ocuklarda-ate" },
    { title: "Çocuklarda Egzama", path: "/bilgi-merkezi/hastaliklar/ocuklarda-egzama" },
    { title: "Orta Kulak İltihabı", path: "/bilgi-merkezi/hastaliklar/orta-kulak-ltihab" },
    { title: "Pişikler", path: "/bilgi-merkezi/hastaliklar/pi-ikler" },
    { title: "Sinüzit", path: "/bilgi-merkezi/hastaliklar/sin-zit" },
    { title: "Yenidoğan Sarılığı", path: "/bilgi-merkezi/hastaliklar/yenido-an-sar-l" }
  ],
  'oyuncaklar': [
    { title: "0 - 6 Ay Oyuncak Kılavuzu", path: "/bilgi-merkezi/oyuncaklar/0-6-ay-oyuncak-k-lavuzu" },
    { title: "1 Yaş - Oyuncak Kılavuzu", path: "/bilgi-merkezi/oyuncaklar/1-ya-oyuncak-k-lavuzu" },
    { title: "6 - 12 Ay Oyuncak Kılavuzu", path: "/bilgi-merkezi/oyuncaklar/6-12-ay-oyuncak-k-lavuzu" },
    { title: "Oyuncak Güvenliği Kılavuzu", path: "/bilgi-merkezi/oyuncaklar/oyuncak-g-venli-i-k-lavuzu" }
  ],
  'aile-medya-plani': [
    { title: "Aile Medya Planı [1] - Medya Dengesi", path: "/bilgi-merkezi/aile-medya-plani/aile-medya-plan-1-medya-dengesi" },
    { title: "Aile Medya Planı [2] - Medya Hakkında Konuşmak", path: "/bilgi-merkezi/aile-medya-plani/aile-medya-plan-2-medya-hakk-nda-konu-mak" },
    { title: "Aile Medya Planı [3] - Nezaket ve Empati", path: "/bilgi-merkezi/aile-medya-plani/aile-medya-plan-3-nezaket-ve-empati" },
    { title: "Aile Medya Planı [4] - Dijital Gizlilik ve Güvenlik", path: "/bilgi-merkezi/aile-medya-plani/aile-medya-plan-4-dijital-gizlilik-ve-g-venlik" },
    { title: "Aile Medya Planı [5] - Ekransız Bölgeler", path: "/bilgi-merkezi/aile-medya-plani/aile-medya-plan-5-ekrans-z-b-lgeler" },
    { title: "Aile Medya Planı [6] - Ekransız Zamanlar", path: "/bilgi-merkezi/aile-medya-plani/aile-medya-plan-6-ekrans-z-zamanlar" },
    { title: "Aile Medya Planı [7] - İyi İçerik Seçme", path: "/bilgi-merkezi/aile-medya-plani/aile-medya-plan-7-yi-erik-se-me" },
    { title: "Aile Medya Planı [8] - Medyayı Birlikte Kullanma", path: "/bilgi-merkezi/aile-medya-plani/aile-medya-plan-8-medyay-birlikte-kullanma" },
    { title: "Aile Medya Planı Şablon", path: "/bilgi-merkezi/aile-medya-plani/aile-medya-plan-ablon" },
    { title: "Medya Kullanımına Yönelik Aile Rehberi", path: "/bilgi-merkezi/aile-medya-plani/medya-kullan-m-na-y-nelik-aile-rehberi" }
  ],
  'genel-bilgiler': [
    { title: "6-8 Ay için Uyku Önerileri", path: "/bilgi-merkezi/genel-bilgiler/6-8-ay-i-in-uyku-nerileri" },
    { title: "Ağlayan Bebek ve Kolik", path: "/bilgi-merkezi/genel-bilgiler/a-layan-bebek-ve-kolik" },
    { title: "Alkol Kullanımı ve Emzirme", path: "/bilgi-merkezi/genel-bilgiler/alkol-kullan-m-ve-emzirme" },
    { title: "Araba Güvenlik Koltukları", path: "/bilgi-merkezi/genel-bilgiler/araba-g-venlik-koltuklar" },
    { title: "Bebeğinizi Emzirmek", path: "/bilgi-merkezi/genel-bilgiler/bebe-inizi-emzirmek" },
    { title: "Bebekler ve Küçük Çocuklarda Sağlıklı Beslenme", path: "/bilgi-merkezi/genel-bilgiler/bebekler-ve-k-k-ocuklarda-sa-l-kl-beslenme" },
    { title: "Bebeklerde Düşmeleri Önleme", path: "/bilgi-merkezi/genel-bilgiler/bebeklerde-d-meleri-nleme" },
    { title: "Bebeklerde ve Çocuklarda Boğulmaları Önleme ve İlk Yardım", path: "/bilgi-merkezi/genel-bilgiler/bebeklerde-ve-ocuklarda-bo-ulmalar-nleme-ve-lk-yard-m" },
    { title: "Beslenme Güvenliği", path: "/bilgi-merkezi/genel-bilgiler/beslenme-g-venli-i" },
    { title: "Bir Ergenle İletişim Kurmanın Yolları", path: "/bilgi-merkezi/genel-bilgiler/bir-ergenle-leti-im-kurman-n-yollar" },
    { title: "Böcek Kovucular", path: "/bilgi-merkezi/genel-bilgiler/b-cek-kovucular" },
    { title: "Çocuğunuzun Ağız ve Diş Sağlığı Hakkında Bilmeniz Gerekenler", path: "/bilgi-merkezi/genel-bilgiler/ocu-unuzun-a-z-ve-di-sa-l-hakk-nda-bilmeniz-gerekenler" },
    { title: "Çocuklar Arası Zorbalık", path: "/bilgi-merkezi/genel-bilgiler/ocuklar-aras-zorbal-k" },
    { title: "Çocuklar için Ev Güvenliği", path: "/bilgi-merkezi/genel-bilgiler/ocuklar-i-in-ev-g-venli-i" },
    { title: "Çocuklar için Giysi Güvenliği", path: "/bilgi-merkezi/genel-bilgiler/ocuklar-i-in-giysi-g-venli-i" },
    { title: "Diş Çıkarma Süreci", path: "/bilgi-merkezi/genel-bilgiler/di-karma-s-reci" },
    { title: "Emzik Bırakma", path: "/bilgi-merkezi/genel-bilgiler/emzik-b-rakma" },
    { title: "Emzik Bırakma İpuçları", path: "/bilgi-merkezi/genel-bilgiler/emzik-b-rakma-pu-lar" },
    { title: "Emzirme İpuçları - Süt Saklama", path: "/bilgi-merkezi/genel-bilgiler/emzirme-pu-lar-s-t-saklama" },
    { title: "Emzirme İpuçları - Yerleşme ve Kavrama", path: "/bilgi-merkezi/genel-bilgiler/emzirme-pu-lar-yerle-me-ve-kavrama" },
    { title: "Ergenlik Dönemi için Ailelere Tavsiyeler", path: "/bilgi-merkezi/genel-bilgiler/ergenlik-d-nemi-i-in-ailelere-tavsiyeler" },
    { title: "Güvenli Uyku ve Bebeğiniz - Ani Bebek Ölümü Sendromu", path: "/bilgi-merkezi/genel-bilgiler/g-venli-uyku-ve-bebe-iniz-ani-bebek-l-m-sendromu" },
    { title: "Siber Zorbalık", path: "/bilgi-merkezi/genel-bilgiler/siber-zorbal-k" },
    { title: "Tuvalet Eğitimi", path: "/bilgi-merkezi/genel-bilgiler/tuvalet-e-itimi" },
    { title: "Yangın Güvenliği ve Yanıklardan Korunma", path: "/bilgi-merkezi/genel-bilgiler/yang-n-g-venli-i-ve-yan-klardan-korunma" },
    { title: "Yenidoğan Sünneti", path: "/bilgi-merkezi/genel-bilgiler/yenido-an-s-nneti" }
  ]
};
