name: i18n Translation Check

on:
  pull_request:
    paths:
      - 'src/**/*.html'
      - 'src/**/*.ts'
      - 'src/assets/i18n/*.json'
  push:
    branches: [master, main]
    paths:
      - 'src/**/*.html'
      - 'src/**/*.ts'
      - 'src/assets/i18n/*.json'

jobs:
  i18n-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run i18n sync check
      run: npm run i18n:sync

    - name: Check for translation changes
      run: |
        if git diff --exit-code src/assets/i18n/*.json; then
          echo "✓ Translations are up to date"
        else
          echo "❌ Translation files need to be updated"
          echo "Run 'npm run i18n:sync' locally and commit the changes"
          git diff src/assets/i18n/*.json
          exit 1
        fi

    - name: Validate translations
      run: npm run i18n:validate

    - name: Generate translation report
      if: always()
      run: |
        if [ -f "src/assets/i18n/validation-report.json" ]; then
          echo "## Translation Report" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          cat src/assets/i18n/validation-report.json >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        fi